### ISSUE TITLE
Feature request: Support for Philips hue?

### ISSUE THREAD

**Issue by OsrsMerchant** [adnapPanda/WIZLights#2]
Any chance this is on a todo list? :D This plugin looks so sick! Good job on it

Terror_nisse

**Comment by adnapPanda** [comment]
This used to be a plugin on the plugin hub actually but it was removed for not being maintained [here](https://github.com/Nick-Anzalone/Hue_Implementation).
I don't think this is in the plans since neither I or my other contributor own Philips lights, so we can't accurately test it.
I guess you could fork the plugin that was removed and try to fix it.
Sorry
